version: '2'
services:
  energyflux-app:
    image: energyflux
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://energyflux-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=EnergyFlux
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  energyflux-mongodb:
    extends:
      file: mongodb.yml
      service: energyflux-mongodb
